# Generated by Django 5.2.1 on 2025-05-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='image',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.task'),
        ),
    ]
