# Generated by Django 5.2.1 on 2025-05-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='marital_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج')], default='single', max_length=10, verbose_name='الحالة الاجتماعية'),
        ),
        migrations.AddField(
            model_name='task',
            name='national_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='رقم البطاقة'),
        ),
        migrations.AddField(
            model_name='task',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='رقم التليفون'),
        ),
    ]
