# Generated by Django 5.2.1 on 2025-05-10 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_task_task_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_done',
            new_name='is_completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('done', 'done')], default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='app.task'),
        ),
    ]
