# Generated by Django 5.2.1 on 2025-05-10 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_todo_create_at_todo_updated_at_todo_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
